# Generated by Django 5.1.5 on 2025-03-25 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('total_employee', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('TECH', 'Technology'), ('FIN', 'Finance'), ('HEALTH', 'Health'), ('EDU', 'Education')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=models.CASCADE, to='invoice.company'),
        ),
    ]
