# Generated by Django 5.1.5 on 2025-03-27 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_company_alter_invoice_id_invoice_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('category', models.CharField(choices=[('GROCERY', 'Grocery'), ('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('COSMETICS', 'Cosmetics'), ('MEDICINES', 'Medicines'), ('BOOKS', 'Books'), ('SPORTS', 'Sports'), ('FURNITURE', 'Furniture'), ('TOYS', 'Toys'), ('STATIONARY', 'Stationary'), ('OTHERS', 'Others')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.company')),
            ],
        ),
    ]
